name: Develop-To-Homol
on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Open PR to Homol
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: homol
          title: Automatically created Pull Request from Develop
          body: This is an automatically created Pull Request triggered by a merge into the develop branch.
          approve-comment: true
  
  merge_homol:
    name: Merge to Homol
    runs-on: ubuntu-latest
    needs: create_pull_request

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge Pull Request
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:PRMerge
          git checkout homol
          git merge PRMerge --no-edit
          git push origin homol
