name: CI
on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR number
      id: pr_number
      run: |
        PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
          | jq -r '.[0].number')
        echo "::set-output name=pr_number::$PR_NUMBER"

      - name: Open PR to Develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          title: Automatically created Pull Request
          body: This is an automatically created Pull Request triggered by a commit in a feature branch.

  merge_develop:
    name: Merge to Develop
    runs-on: ubuntu-latest
    needs: create-pull-request

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge Pull Request
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin pull/${{ needs.deploy.outputs.pr_number }}/merge:PRMerge
          git checkout develop
          git merge PRMerge --no-edit
          git push origin develop